import Agito from "@/components/images/guides/tyrants/Agito.png";
import Agnes from "@/components/images/guides/tyrants/Agnes.png";
import Albin from "@/components/images/guides/tyrants/Albin.png";
import Alfombra from "@/components/images/guides/tyrants/Alfombra.png";
import Angelita from "@/components/images/guides/tyrants/Angelita.png";
import Aria from "@/components/images/guides/tyrants/Aria.png";
import Asana from "@/components/images/guides/tyrants/Asana.png";
import Badul from "@/components/images/guides/tyrants/Badul.png";
import Barnabas from "@/components/images/guides/tyrants/Barnabas.png";
import Belenguer from "@/components/images/guides/tyrants/Belenguer.png";
import Bertrand from "@/components/images/guides/tyrants/Bertrand.png";
import Brandys from "@/components/images/guides/tyrants/Brandys.png";
import Caesar from "@/components/images/guides/tyrants/Caesar.png";
import Camus from "@/components/images/guides/tyrants/Camus.png";
import Casper from "@/components/images/guides/tyrants/Casper.png";
import Claire from "@/components/images/guides/tyrants/Claire.png";
import Climati from "@/components/images/guides/tyrants/Climati.png";
import Daril from "@/components/images/guides/tyrants/Daril.png";
import Dieter from "@/components/images/guides/tyrants/Dieter.png";
import Draken from "@/components/images/guides/tyrants/Draken.png";
import Duran from "@/components/images/guides/tyrants/Duran.png";
import Edgardo from "@/components/images/guides/tyrants/Edgardo.png";
import Elena from "@/components/images/guides/tyrants/Elena.png";
import Ernest from "@/components/images/guides/tyrants/Ernest.png";
import Eutropio from "@/components/images/guides/tyrants/Eutropio.png";
import Ferdinand from "@/components/images/guides/tyrants/Ferdinand.png";
import Florence from "@/components/images/guides/tyrants/Florence.png";
import Gauhl from "@/components/images/guides/tyrants/Ga-uhl.png";
import Germaine from "@/components/images/guides/tyrants/Germaine.png";
import Giraffin from "@/components/images/guides/tyrants/Giraffin.png";
import Gugli from "@/components/images/guides/tyrants/Gugli.png";
import Hayreddin from "@/components/images/guides/tyrants/Hayreddin.png";
import Heidi from "@/components/images/guides/tyrants/Heidi.png";
import Ilithios from "@/components/images/guides/tyrants/Ilithios.png";
import Jarosch from "@/components/images/guides/tyrants/Jarosch.png";
import Joker from "@/components/images/guides/tyrants/Joker.png";
import Lambert from "@/components/images/guides/tyrants/Lambert.png";
import Leandro from "@/components/images/guides/tyrants/Leandro.png";
import Lockhart from "@/components/images/guides/tyrants/Lockhart.png";
import Ludvik from "@/components/images/guides/tyrants/Ludvik.png";
import Manuelita from "@/components/images/guides/tyrants/Manuelita.png";
import Natt from "@/components/images/guides/tyrants/Natt.png";
import Oskar from "@/components/images/guides/tyrants/Oskar.png";
import Pizelle from "@/components/images/guides/tyrants/Pizelle.png";
import Poppy from "@/components/images/guides/tyrants/Poppy.png";
import Rajidi from "@/components/images/guides/tyrants/Rajidi.png";
import Roderick from "@/components/images/guides/tyrants/Roderick.png";
import Roimi from "@/components/images/guides/tyrants/Roimi.png";
import Sacrum from "@/components/images/guides/tyrants/Sacrum.png";
import Sadar from "@/components/images/guides/tyrants/Sadar.png";
import Schneider from "@/components/images/guides/tyrants/Schneider.png";
import Seti from "@/components/images/guides/tyrants/Seti.png";
import Siel from "@/components/images/guides/tyrants/Si-el.png";
import Squallo from "@/components/images/guides/tyrants/Squallo.png";
import Telethia from "@/components/images/guides/tyrants/Telethia.png";
import Tico from "@/components/images/guides/tyrants/Tico.png";
import Truppe from "@/components/images/guides/tyrants/Truppe.png";
import Uluora from "@/components/images/guides/tyrants/Uluora.png";
import Unlimited from "@/components/images/guides/tyrants/Unlimited.png";
import Vainamo from "@/components/images/guides/tyrants/Vainamo.png";
import Valyrian from "@/components/images/guides/tyrants/Valyrian.png";
import Vilem from "@/components/images/guides/tyrants/Vilem.png";
import Vortice from "@/components/images/guides/tyrants/Vortice.png";
import Xair from "@/components/images/guides/tyrants/Xair.png";
import Yelena from "@/components/images/guides/tyrants/Yelena.png";
import Yuiro from "@/components/images/guides/tyrants/Yuiro.png";
import Zohan from "@/components/images/guides/tyrants/Zohan.png";
import Zorn from "@/components/images/guides/tyrants/Zorn.png";

var TyrantsData = [
  {
    id: "agito",
    img: Agito,
    name: "Agito, the Golden",
    category: "Insectoid",
    species: "Blatta",
    level: "36 - 40",
    region: "Primordia",
    location: "Shadow Rise",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "agnes",
    img: Agnes,
    name: "Agnes, the Divine-Scaled",
    category: "Theroids",
    species: "Tersqual",
    level: "67",
    region: "Cauldros",
    location: "FN Site 506",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "albin",
    img: Albin,
    name: "Albin, the Wicked Meddler",
    category: "Piscinoids",
    species: "Purgovent",
    level: "56",
    region: "Sylvalum",
    location: "Lake Ciel",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "alfombra",
    img: Alfombra,
    name: "Alfombra, the Transcendent",
    category: "Insectoids",
    species: "Tectinsula",
    level: "14",
    region: "Noctilum",
    location: "Humdrum Peaks",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "angelita",
    img: Angelita,
    name: "Angelita, the Blade Bouquet",
    category: "Insectoids",
    species: "Sacrifole",
    level: "61",
    region: "Cauldros",
    location: "M'gando Mineral Spring",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "aria",
    img: Aria,
    name: "Aria, the Zauberflöte",
    category: "Theroids",
    species: "Saltat",
    level: "13",
    region: "Noctilum",
    location: "Rust Lake",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "asana",
    img: Asana,
    name: "Asana, the Azure Star",
    category: "Theroids",
    species: "Cervus",
    level: "30",
    region: "Sylvalum",
    location: "Lake Ciel",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "badul",
    img: Badul,
    name: "Badul, the One-Eyed",
    category: "Humanoids",
    species: "Milsaadi",
    level: "46",
    region: "Sylvalum",
    location: "Hilal Stronghold",
    time: "5:00 - 17:00",
    weather: "All",
  },
  {
    id: "barnabas",
    img: Barnabas,
    name: "Barnabas, the Despot",
    category: "Theroids",
    species: "Vigent",
    level: "65",
    region: "Oblivia",
    location: "Aaroy Plain",
    time: "5:00 - 17:00",
    weather: "All",
  },
  {
    id: "belenguer",
    img: Belenguer,
    name: "Belenguer, the Gunhammer",
    category: "Insectoids",
    species: "Ictus",
    level: "30",
    region: "Oblivia",
    location: "King's Falls",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "bertrand",
    img: Bertrand,
    name: "Bertrand, the Gorge Scourge",
    category: "Insectoids",
    species: "Adsecula",
    level: "57",
    region: "Oblivia",
    location: "East Ibra Ravine",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "brandys",
    img: Brandys,
    name: "Brandys, the Spectral Light",
    category: "Piscinoids",
    species: "Xiphias",
    level: "45",
    region: "Sylvalum",
    location: "Behemoth's Shadows",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "caesar",
    img: Caesar,
    name: "Caesar, the Hundred-Eyed",
    category: "Insectoids",
    species: "Petramand",
    level: "68",
    region: "Primordia",
    location: "Stonelattice Cavern",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "camus",
    img: Camus,
    name: "Camus, the Treasured",
    category: "Insectoids",
    species: "Blatta",
    level: "46 - 50",
    region: "Cauldros",
    location: "Bestial Utopia",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "casper",
    img: Casper,
    name: "Casper, the Unhealthy Eater",
    category: "Insectoids",
    species: "Blatta",
    level: "13",
    region: "Primordia",
    location: "West Gate Plain",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "claire",
    img: Claire,
    name: "Claire, the Sheltered",
    category: "Theroids",
    species: "Ovis",
    level: "60",
    region: "Noctilum",
    location: "Narcissus Tree",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "climati",
    img: Climati,
    name: "Climati, the Chilling Wind",
    category: "Humanoids",
    species: "Sylooth",
    level: "30",
    region: "Oblivia",
    location: "Central Ibra Ravine",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "daril",
    img: Daril,
    name: "Daril, the Eradicator",
    category: "Humanoids",
    species: "Marnuck",
    level: "29",
    region: "Primordia",
    location: "Castaway Cavern",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "dieter",
    img: Dieter,
    name: "Dieter, the Epicure",
    category: "Theroids",
    species: "Grex",
    level: "39",
    region: "Primordia",
    location: "Talon Rock Second Terrane",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "draken",
    img: Draken,
    name: "Draken, the Drifting Cloud",
    category: "Piscinoids",
    species: "Balaena",
    level: "85",
    region: "Primordia",
    location: "Primordia Waters",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "duran",
    img: Duran,
    name: "Duran, the Draconian",
    category: "humanoids",
    species: "Marnuck",
    level: "38",
    region: "Cauldros",
    location: "O'rrh Sim Castle Remains",
    time: "5:00 - 0:00",
    weather: "All",
  },
  {
    id: "edgardo",
    img: Edgardo,
    name: "Edgardo, the Carefree",
    category: "Insectoids",
    species: "Thallus",
    level: "18",
    region: "Oblivia",
    location: "North Coast",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "elena",
    img: Elena,
    name: "Elena, the Infernal",
    category: "Insectoids",
    species: "Scirpo",
    level: "79",
    region: "Noctilum",
    location: "Weeping Whitewood",
    time: "Anytime",
    weather: "Dense Fog",
  },
  {
    id: "ernest",
    img: Ernest,
    name: "Ernest, the Contemplative",
    category: "Theroids",
    species: "Progen",
    level: "36",
    region: "Oblivia",
    location: "King's Falls",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "eutropio",
    img: Eutropio,
    name: "Eutropio, the Sea Rumble",
    category: "Insectoids",
    species: "Levitath",
    level: "45",
    region: "Primordia",
    location: "Seaswept Ridge",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "ferdinand",
    img: Ferdinand,
    name: "Ferdinand, the Fortuitous",
    category: "Theroids",
    species: "Mephite",
    level: "28",
    region: "Oblivia",
    location: "Lake Basel",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "florence",
    img: Florence,
    name: "Florence, the Hell Maggot",
    category: "Insectoids",
    species: "Germivore",
    level: "24",
    region: "Sylvalum",
    location: "Hilal Meadow",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "ga-uhl",
    img: Gauhl,
    name: "Ga-uhl, the Precept-Keeper",
    category: "Mechanoids",
    species: "Fal-swo",
    level: "50",
    region: "Sylvalum",
    location: "Badr Stronghold",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "germaine",
    img: Germaine,
    name: "Germaine, the Treasure Keeper",
    category: "Theroids",
    species: "Ovis",
    level: "35",
    region: "Oblivia",
    location: "Eddie's Conquest",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "giraffin",
    img: Giraffin,
    name: "Giraffin, the Old Hand",
    category: "Theroids",
    species: "Lepyx",
    level: "41",
    region: "Sylvalum",
    location: "South Silent Sandsea",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "gugli",
    img: Gugli,
    name: "Gugli, the Relentless",
    category: "Theroids",
    species: "Suid",
    level: "20",
    region: "Primordia",
    location: "Janpath Lake",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "hayreddin",
    img: Hayreddin,
    name: "Hayreddin, the Territorial",
    category: "Theroids",
    species: "Simius",
    level: "81",
    region: "Primordia",
    location: "East Gate Plain",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "heidi",
    img: Heidi,
    name: "Heidi, the Lively",
    category: "Theroids",
    species: "Ovis",
    level: "60",
    region: "Noctilum",
    location: "Narcissus Tree",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "ilithios",
    img: Ilithios,
    name: "Ilithios, the Enlightened",
    category: "Humanoids",
    species: "Gularth",
    level: "48",
    region: "Cauldros",
    location: "Sunset Falls",
    time: "Anytime",
    weather: "All (except Brimstone Rain)",
  },
  {
    id: "jarosch",
    img: Jarosch,
    name: "Jarosch, the Sensational",
    category: "Theroids",
    species: "Saltat",
    level: "23",
    region: "Noctilum",
    location: "Potter's Rock",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "joker",
    img: Joker,
    name: "Joker, the Unknowable",
    category: "Insectoids",
    species: "Blatta",
    level: "90",
    region: "Noctilum",
    location: "Divine Roost",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "lambert",
    img: Lambert,
    name: "Lambert, the Divine Wind",
    category: "Theroids",
    species: "Insidia",
    level: "15",
    region: "Noctilum",
    location: "Goblin's Narrow",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "leandro",
    img: Leandro,
    name: "Leandro, the Sneering",
    category: "Theroids",
    species: "Cantor",
    level: "49",
    region: "Sylvalum",
    location: "Behemoth's Shadows",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "lockhart",
    img: Lockhart,
    name: "Lockhart, the Killer of Hope",
    category: "Insectoids",
    species: "Vivohast",
    level: "52",
    region: "Sylvalum",
    location: "Lake Ciel",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "ludvik",
    img: Ludvik,
    name: "Ludvik, the Picky Eater",
    category: "Theroids",
    species: "Evello",
    level: "29",
    region: "Oblivia",
    location: "Keegan Ridge",
    time: "Daytime",
    weather: "All",
  },
  {
    id: "manuelita",
    img: Manuelita,
    name: "Manuelita, the Affectionate",
    category: "Theroids",
    species: "Suid",
    level: "47",
    region: "Noctilum",
    location: "Middle Hushflood",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "natt",
    img: Natt,
    name: "Natt, the Inestimable",
    category: "Insectoids",
    species: "Blatta",
    level: "41 - 45",
    region: "Cauldros",
    location: "FN Site 507",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "oskar",
    img: Oskar,
    name: "Oskar, the Summer Squall",
    category: "Theroids",
    species: "Aprica",
    level: "11",
    region: "Noctilum",
    location: "Old Dragontail Tree",
    time: "5:00 - 17:00",
    weather: "All",
  },
  {
    id: "pizelle",
    img: Pizelle,
    name: "Pizelle, the Purple Lightning",
    category: "Insectoids",
    species: "Thallus",
    level: "40",
    region: "Noctilum",
    location: "Dead Man's Ingress",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "poppy",
    img: Poppy,
    name: "Poppy, the Pyromaniac",
    category: "Piscinoids",
    species: "Visigel",
    level: "36",
    region: "Cauldros",
    location: "Infernal Ledges",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "rajidi",
    img: Rajidi,
    name: "Rajidi, the Cumuliform",
    category: "Piscinoids",
    species: "Balaena",
    level: "52",
    region: "Primordia",
    location: "FN Site 121",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "roderick",
    img: Roderick,
    name: "Roderick, the Fleet-Footed",
    category: "Theroids",
    species: "Evello",
    level: "11",
    region: "Primordia",
    location: "East Gate Plain",
    time: "5:00 - 17:00",
    weather: "All",
  },
  {
    id: "roimi",
    img: Roimi,
    name: "Roimi, the Affluent",
    category: "Insectoids",
    species: "Blatta",
    level: "31 - 35",
    region: "Primordia",
    location: "Janpath Lake",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "sacrum",
    img: Sacrum,
    name: "Sacrum, the Noctilucent",
    category: "Insectoids",
    species: "Papil",
    level: "50",
    region: "Noctilum",
    location: "Whale's Weeper",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "sadar",
    img: Sadar,
    name: "Sadar, the Unhinged",
    category: "Humanoids",
    species: "Marnuck",
    level: "35",
    region: "Sylvalum",
    location: "Hilal Stronghold",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "schneider",
    img: Schneider,
    name: "Schneider, the Cliffpercher",
    category: "Insectoids",
    species: "Forfex",
    level: "10",
    region: "Noctilum",
    location: "FN Site 212",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "seti",
    img: Seti,
    name: "Seti, the Light of Stars",
    category: "Theroids",
    species: "Cervus",
    level: "50",
    region: "Noctilum",
    location: "Whale's Weeper",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "si-el",
    img: Siel,
    name: "Si-el, the Vacuous",
    category: "Mechanoids",
    species: "Oc-serv",
    level: "19",
    region: "Noctilum",
    location: "Qing Long Glade",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "squallo",
    img: Squallo,
    name: "Squallo, the Sand Mirer",
    category: "Insectoids",
    species: "Sabula",
    level: "65",
    region: "Oblivia",
    location: "Big Arch",
    time: "5:00 - 17:00",
    weather: "All",
  },
  {
    id: "telethia",
    img: Telethia,
    name: "Telethia, the Endbringer",
    category: "Ultrafauna",
    species: "Telethia",
    level: "99",
    region: "Noctilum",
    location: "Divine Roost",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "tico",
    img: Tico,
    name: "Tico, the Precious",
    category: "Insectoids",
    species: "Blatta",
    level: "26 - 30",
    region: "Oblivia",
    location: "Beehive Rock",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "truppe",
    img: Truppe,
    name: "Truppe, the Ceaseless Dark",
    category: "Insectoids",
    species: "Petramand",
    level: "53",
    region: "Cauldros",
    location: "Old Ceremonial Hollow",
    time: "17:00 - 5:00",
    weather: "All",
  },
  {
    id: "uluora",
    img: Uluora,
    name: "Uluora, the Burgeoning",
    category: "Theroids",
    species: "Monoceros",
    level: "22",
    region: "Cauldros",
    location: "Emerian Battlegrounds",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "unlimited",
    img: Unlimited,
    name: "Unlimited Output Zig",
    category: "Mechanoids",
    species: "Zig",
    level: "43",
    region: "Cauldros",
    location: "Sunset Falls",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "vainamo",
    img: Vainamo,
    name: "Vainamo, the Bellower",
    category: "Theroids",
    species: "Vigent",
    level: "39",
    region: "Cauldros",
    location: "Capital Wreckage",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "valyrian",
    img: Valyrian,
    name: "Valyrian, the Iron Cleaver",
    category: "Insectoids",
    species: "Ictus",
    level: "48",
    region: "Oblivia",
    location: "Alexander Ridge",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "vilem",
    img: Vilem,
    name: "Vilem, the Gold-Scaled",
    category: "Piscinoids",
    species: "Aetrygon",
    level: "45",
    region: "Oblivia",
    location: "Lake Basel",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "vortice",
    img: Vortice,
    name: "Vortice, the Deific Blast",
    category: "Piscinoids",
    species: "Colubrim",
    level: "94",
    region: "Cauldros",
    location: "Mount M'gando",
    time: "Anytime",
    weather: "Brimstone Rain",
  },
  {
    id: "xair",
    img: Xair,
    name: "Xair, the Cerulean Walker",
    category: "Theroids",
    species: "Coronid",
    level: "75",
    region: "Sylvalum",
    location: "Sylvalum Waters",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "yelena",
    img: Yelena,
    name: "Yelena, the Sequestered",
    category: "Insectoids",
    species: "Scirpo",
    level: "34",
    region: "Primordia",
    location: "East Janpath Plain",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "yuiro",
    img: Yuiro,
    name: "Yuiro, the Luxuriant",
    category: "Insectoids",
    species: "Blatta",
    level: "51 - 55",
    region: "Noctilum",
    location: "Great Nail",
    time: "Anytime",
    weather: "All",
  },
  {
    id: "zohan",
    img: Zohan,
    name: "Zohan, the Thunderbolt",
    category: "Piscinoids",
    species: "Scintimure",
    level: "64",
    region: "Sylvalum",
    location: "Delusians North Summit",
    time: "Anytime",
    weather: "Spores",
  },
  {
    id: "zorn",
    img: Zorn,
    name: "Zorn, the Wanderer",
    category: "Theroids",
    species: "Saltat",
    level: "56",
    region: "Cauldros",
    location: "Old Ceremonial Hollow",
    time: "Anytime",
    weather: "Rainbows",
  },
];

export default TyrantsData;
