import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="App">
          <NavBar />
          {children}
          {/* <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/NLA" element={<NLA />} />
            <Route path="/destinations" element={<Destinations />} />
            <Route path="/guides" element={<Guides />} />
            <Route path="/FAQs" element={<FAQs />} />
            <Route path="/destinations/primordia" element={<Primordia />} />
            <Route path="/destinations/noctilum" element={<Noctilum />} />
            <Route path="/destinations/oblivia" element={<Oblivia />} />
            <Route path="/destinations/sylvalum" element={<Sylvalum />} />
            <Route path="/destinations/cauldros" element={<Cauldros />} />
          </Routes> */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
